services:
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: always
    hostname: "ubuntu"
    user: 1001:988
    env_file:
      - .env.telegraf
    networks:
      - monitoring
    volumes:
      - /:/hostfs:ro
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  monitoring:
    driver: bridge
